# No restrictions, no quarantine

# === Simulation parameters ===

min_inhabitants: 0
simulation_days: 360

# === Population ===

mean_stochastic_interactions: 15
#social_network_daily_ratio: 0.5
suprespreader_ratio: 0
respect_quarantine: 0.8
quarantine_effifiency: 0.8
quarantine_length: 14

lockdown_ratio: 0.05
trace_contacts: false

# === Restrictions ===

restrictions:
  - __type__: Interactions
    day_start: 20
    day_end: 80
    ratio: 0.05
  - __type__: travel
    day_start: 0
    day_end: 360
    ratio: 0.74

# === Medical ===

n_tests_daily: 0
n_icu_beds: 1000

# === Parameters of the virus ===

virus:
  name: SARS-CoV2
  transmission_probability: 0.0115
  household_transmission_probability: 0.064
  infectious_days_mean: 6.5
  infectious_days_std: 1

# === Symptoms ===

ratio_symptomatic: 0.6

infectious_start_mean: 5.1
infectious_start_std: 1

hospitalization_start_mean: 10
hospitalization_start_std: 1.5

hospitalization_length_mean: 8
hospitalization_length_std: 1

critical_care_start_mean: 6
critical_care_start_std: 1.5

critical_care_length_mean: 10
critical_care_length_std: 1

# === Inputs ===

migration_matrix: data/sensitive/OD_final.pickle
populations_file: data/munic_pop.xlsx
town_locations_file: data/obce1.xlsx
age_distribution: data/age_distribution.json
age_symptoms: data/age_symptoms.json
household_distribution: data/households.json
social_network: data/social/generated/watts_strogatz_triple_big.json

# === Outputs ===

result_file: results/blackout.json

# === Plotting ===

individual_cities:
  dir: plots/blackout
  cities:
    - Martin
    - Nitra
    - Trenčín
    - Trnava
    - Banská Bystrica
    - Žilina
    - Poprad
    - Prešov
    - Bratislava-Ružinov
    - Bratislava-Petržalka

check_plots: plots/blackout/checks

geographical:
  precision: 500
  timeseries_dir: plots/geographical/blackout

n_processes: 12
