# === Simulation parameters ===

min_inhabitants: 0
simulation_days: 200

# === Population ===

mean_stochastic_interactions: 4.3
social_network_daily_ratio: 0.5
suprespreader_ratio: 0.05
respect_quarantine: 0
quarantine_length: 14

# === Restrictions ===

restrictions:
  - __type__: Interactions
    day_start: 10
    day_end: 500
    ratio: 0.6

# === Medical ===

n_tests_daily: 0
n_icu_beds: 1000

# === Parameters of the virus ===

virus:
  name: SARS-CoV2
  transmission_probability: 0.0165
  household_transmission_probability: 0.025
  infectious_days_mean: 6.5
  infectious_days_std: 1

# === Symptoms ===

ratio_symptomatic: 0.6

infectious_start_mean: 5.1
infectious_start_std: 1

hospitalization_start_mean: 10
hospitalization_start_std: 1.5

hospitalization_length_mean: 8
hospitalization_length_std: 1

critical_care_start_mean: 6
critical_care_start_std: 1.5

critical_care_length_mean: 10
critical_care_length_std: 1

# === Inputs ===

migration_matrix: data/sensitive/OD_final.pickle
populations_file: data/munic_pop.xlsx
town_locations_file: data/obce1.xlsx
age_distribution: data/age_distribution.json
age_symptoms: data/age_symptoms.json
household_distribution: data/households.json
social_network: data/social/generated/watts_strogatz_triple_big.json

# === Outputs ===

result_file: results/watts_strogatz_triple.json

# === Plotting ===

individual_cities:
  dir: plots/watts_strogatz_triple
  cities:
    - Martin
    - Nitra
    - Trenčín
    - Trnava
    - Banská Bystrica
    - Žilina
    - Poprad
    - Prešov
    - Bratislava-Ružinov
    - Bratislava-Petržalka

check_plots: plots/watts_strogatz_triple/checks

geographical:
  precision: 500
  timeseries_dir: plots/geographical/watts_strogatz_triple

n_processes: 12
