# === Simulation parameters ===

min_inhabitants: 0
simulation_days: 240
n_tests_daily: 1500

population:
  mean_periodic_interactions: 0
  mean_stochastic_interactions: 15
  respect_quarantine: 0.6  # ratio of people with symptoms, who stay at home
  ratio_symptomatic: 0.6


# === Parameters of the virus ===

virus:
  name: SARS-CoV2
  transmission_probability: 0.0165
  household_transmission_probability: 0.025
  infectious_days_mean: 6.5
  infectious_days_std: 1

# mean time after which a person who contracted the virus
# starts being infectious
infectious_start_mean: 5
infectious_start_std: 1

# mean time after which a person who contracted the virus
# starts needing hospitalization
hospitalization_start_mean: 10
hospitalization_start_std: 1.5

hospitalization_length_mean: 8
hospitalization_length_std: 1

critical_care_start_mean: 6
critical_care_start_std: 1.5

critical_care_length_mean: 10
critical_care_length_std: 1

# === inputs ===

migration_matrix: data/sensitive/OD_final.pickle
populations_file: data/sensitive/munic_pop.xlsx
town_locations_file: data/sensitive/obce1.xlsx
age_distribution: data/age_distribution.json
age_symptoms: data/age_symptoms.json
household_distribution: data/households.json

# === outputs ===

result_file: results/current-restrictions.json

# === Plotting ===

individual_cities:
  dir: plots/current-restrictions
  cities:
    - Martin
    - Nitra
    - Trenčín
    - Trnava
    - Banská Bystrica
    - Žilina
    - Poprad
    - Prešov
    - Bratislava-Ružinov
    - Bratislava-Petržalka

check_plots: plots/current-restrictions/checks

geographical:
  precision: 500
  timeseries_dir:
    plots/geographical/current-restrictions

n_processes: 12
