# No restrictions, no quarantine

# === Simulation parameters ===

min_inhabitants: 0
simulation_days: 460

# === Population ===

mean_stochastic_interactions: 3.2
social_network_daily_ratio: 0.8
suprespreader_ratio: 0.05
respect_quarantine: 0.9
quarantine_effifiency: 0.9
quarantine_length: 14

lockdown_ratio: 0.05
trace_contacts: true

# === Restrictions ===

restrictions:
  - __type__: Interactions
    day_start: 0
    day_end: 20
    ratio: 0.4
  - __type__: Interactions
    day_start: 20
    day_end: 460
    ratio: 0.75
  - __type__: Travel
    day_start: 0
    day_end: 460
    ratio: 0.4
  - __type__: AdaptiveTravel
    threshold: 0.001
    duration: 60
    ratio: 0.05
  - __type__: AdaptiveInteractions
    threshold: 0.001
    duration: 60
    ratio: 0.05

# === Medical ===

n_tests_daily: 0
n_icu_beds: 1000

# === Parameters of the virus ===

virus:
  name: SARS-CoV2
  transmission_probability: 0.0132
  household_transmission_probability: 0.025
  infectious_days_mean: 6.5
  infectious_days_std: 1

# === Symptoms ===

ratio_symptomatic: 0.6

infectious_start_mean: 5.1
infectious_start_std: 1

hospitalization_start_mean: 10
hospitalization_start_std: 1.5

hospitalization_length_mean: 8
hospitalization_length_std: 1

critical_care_start_mean: 6
critical_care_start_std: 1.5

critical_care_length_mean: 10
critical_care_length_std: 1

# === Inputs ===

migration_matrix: data/sensitive/OD_final.pickle
populations_file: data/munic_pop.xlsx
town_locations_file: data/obce1.xlsx
age_distribution: data/age_distribution.json
age_symptoms: data/age_symptoms.json
household_distribution: data/households.json
social_network: data/social/generated/watts_strogatz_triple.json

# === Outputs ===

result_file: results/current_restrictions.json

# === Plotting ===

individual_cities:
  dir: plots/current_restrictions
  cities:
    - Martin
    - Nitra
    - Trenčín
    - Trnava
    - Banská Bystrica
    - Žilina
    - Poprad
    - Prešov
    - Bratislava-Ružinov
    - Bratislava-Petržalka

check_plots: plots/current_restrictions/checks

geographical:
  precision: 500
  timeseries_dir: plots/geographical/current_restrictions

n_processes: 12
