# === Simulation parameters ===

min_inhabitants: 20000
simulation_days: 160
n_processes: 2

population:
  mean_periodic_interactions: 2
  mean_stochastic_interactions: 18

# === Parameters of the virus ===

virus:
  name: SARS-CoV2
  transmission_probability: 0.01639
  infectious_days_mean: 6.5
  infectious_days_std: 1

# mean time after which a person who contracted the virus
# starts being infectious
infectious_start: 5

# mean time after which a person who contracted the virus
# starts needing hospitalization
hospitalization_start: 10

hospitalization_percentage: 0.1

# === inputs ===

migration_matrix: data/sensitive/OD_final.pickle
populations_file: data/sensitive/munic_pop.xlsx
town_locations_file: data/sensitive/obce1.xlsx

# === outputs ===

result_file: results/cities-20000-18.json

# === Plotting ===

individual_cities:
  dir: plots/individual-20000-18
  cities:
    - Martin
    - Nitra
    - Trenčín
    - Trnava
    - Banská Bystrica
    - Žilina
    - Poprad
    - Prešov
    - Bratislava-Ružinov
    - Bratislava-Petržalka

geographical:
  precision: 500
  timeseries_dir:
    plots/geographical/timeseries-20000-18