# === Simulation parameters ===

min_inhabitants: 50000
simulation_days: 120
n_processes: 12

population:
  mean_periodic_interactions: 2
  mean_stochastic_interactions: 20

# === Parameters of the virus ===

virus:
  name: SARS-CoV2
  transmission_probability: 0.01639
  infectious_days_mean: 6.5
  infectious_days_std: 1

# === inputs ===

migration_matrix: data/sensitive/OD_final.pickle
populations_file: data/sensitive/munic_pop.xlsx
town_locations_file: data/sensitive/obce1.xlsx

# === outputs ===

result_file: results/single-city.json