# === Simulation parameters ===

min_inhabitants: 0
simulation_days: 160

population:
  mean_periodic_interactions: 0
  mean_stochastic_interactions: 10

# === Parameters of the virus ===

virus:
  name: SARS-CoV2
  transmission_probability: 0.015
  household_transmission_probability: 0.05
  infectious_days_mean: 6.5
  infectious_days_std: 1

# mean time after which a person who contracted the virus
# starts being infectious
infectious_start_mean: 5
infectious_start_std: 1

# mean time after which a person who contracted the virus
# starts needing hospitalization
hospitalization_start_mean: 10
hospitalization_start_std: 1.5

critical_care_start_mean: 3
critical_care_start_std: 1.5

# === inputs ===

migration_matrix: data/sensitive/OD_final.pickle
populations_file: data/sensitive/munic_pop.xlsx
town_locations_file: data/sensitive/obce1.xlsx
age_distribution: data/age_distribution.json
age_symptoms: data/age_symptoms.json
household_distribution: data/households.json

# === outputs ===

result_file: results/restrictions-60-elderly-limited.json

# === Plotting ===

individual_cities:
  dir: plots/restrictions-60-elderly-limited
  cities:
    - Martin
    - Nitra
    - Trenčín
    - Trnava
    - Banská Bystrica
    - Žilina
    - Poprad
    - Prešov
    - Bratislava-Ružinov
    - Bratislava-Petržalka

geographical:
  precision: 500
  timeseries_dir:
    plots/geographical/restrictions-60-elderly-limited

n_processes: 12
